version: "3.3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./log/traefik.log:/traefik.log
      - ./log/access.log:/access.log
    command:
      ## Dashboard
      - "--api.dashboard=${TRAEFIK_DASHBOARD}"
      ## Providers
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--providers.docker.network=traefik_proxy"
      ## Entrypoints
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.https.address=:443"
      ## Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.caserver=${TRAEFIK_LA_SERVER}"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_LA_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      ## Logging
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--log.format=json"
      - "--accesslog.filepath=/access.log"
      - "--accesslog.format=json"
      - "--accesslog.filters.statusCodes=300-308,400-403,405-499,500-526"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD}"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${APP_BASE_URL}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.entrypoints=https"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"

      # Frontend
      - "traefik.http.routers.frontend.rule=Host(`portainer.${APP_BASE_URL}`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.${APP_BASE_URL}`)"
      - "traefik.http.routers.edge.entrypoints=https"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=letsencrypt"

volumes:
  portainer_data:

networks:
  traefik_proxy:
    external: true